version: 2
updates:
  - package-ecosystem: pip
    directory: /ingestion_service
    schedule:
      interval: weekly
    groups:
      python-deps:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /processor_service
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /query_service
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
